language: node_js
node_js:
- node
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: plgVqMwW22O2BOkYVYGTdY95aanBwxRo3MimolhMSlTO+GvSDMBspf2YY5Goz6Rx6COMo3naFVw6HupkBG1KM6ZNcZ0LtnV0c98rzemppHygtf/htiSh3kO7wZUv3W7KFY/ioBQLr30dCO4P15PY5dG/2V0ChdBwK7h7O4MGpbTzHIkd3YpN74kQzZLkGZQuFg9h9B0wGTj2y5TQOG7ZhKeIED+Qro2iOABGOwlup9Rl/0Qy3eLxQRd7tNOg2MGqbkLBmNtqvRalkVTnevqRTEzLJpvtaDjv+1pTRSFCXyTPgx5bJ35ZVLoblmw8JVoX3uYUi2J/SzR3h9XtzxI//p0qN0M7ttUHIQCL0TWpEXOsx1uDmotpXVLhuxdTpW4OlekJiDg2FTYot91K/Ell9//wxNfTmdu/2PhDUoqk0hqGHVlYvSn9OymTkflY81X2eilnozQKOOCtD7c52as2voGDeeMtxdViQoajsLTtHuJl3AOZKaTuL5lPPs+B+u0nhsMpsLA8MyEZYaf86IlInvMFTKzoUvAiOxZyAwdVqL/RC9xtIaaayxXlT19U+K96pwTNXl5dE/v2W7TyOOu5y52Lsglr8l2VMfGRWz2Fix0+2/o/yLxmMaVNeB/oXsCPaC1XBT9aczPZDn0ePsveh168/GI6/MQZz/LnNp1DMpM=
  app: eras-frontend
  skip_cleanup: true
  on: main
